'use server';

/**
 * @fileOverview AI-powered compliment generator.
 *
 * - generateAICompliment - A function that generates an absurd, over-the-top compliment.
 * - GenerateAIComplimentInput - The input type for the generateAICompliment function (currently empty).
 * - GenerateAIComplimentOutput - The return type for the generateAICompliment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAIComplimentInputSchema = z.object({});
export type GenerateAIComplimentInput = z.infer<typeof GenerateAIComplimentInputSchema>;

const GenerateAIComplimentOutputSchema = z.object({
  compliment: z.string().describe('An absurd, over-the-top compliment generated by AI.'),
});
export type GenerateAIComplimentOutput = z.infer<typeof GenerateAIComplimentOutputSchema>;

export async function generateAICompliment(
  input: GenerateAIComplimentInput
): Promise<GenerateAIComplimentOutput> {
  return generateAIComplimentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAIComplimentPrompt',
  input: {schema: GenerateAIComplimentInputSchema},
  output: {schema: GenerateAIComplimentOutputSchema},
  prompt: `You are an AI that generates absurd and over-the-top compliments. The compliments should be funny and exaggerated, but not completely nonsensical.

  Generate a single, unique compliment.

  Example: "Your elbows are at a perfect 90-degree angle."
  Example: "You have the same number of teeth as a full-grown platypus."
  Example: "Your shadow has excellent posture."
  `,
});

const generateAIComplimentFlow = ai.defineFlow(
  {
    name: 'generateAIComplimentFlow',
    inputSchema: GenerateAIComplimentInputSchema,
    outputSchema: GenerateAIComplimentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
